import { IBook } from '../types/books';

export const mockBooks: IBook[] = [
  {
    isbn13: '9780743273565',
    title: 'The Great Gatsby',
    original_title: 'The Great Gatsby',
    authors: ['F. Scott Fitzgerald'],
    original_publication_year: 1925,
    average_rating: 4.6,
    ratings_count: 5,
    ratings_1: 5.0,
    ratings_2: 3.5,
    ratings_3: 5.0,
    ratings_4: 4.5,
    ratings_5: 5.0,
    image_url: '/assets/images/gatsby.jpg',
    small_image_url: '/assets/images/gatsby.jpg',
  },
  {
    isbn13: '9780061120084',
    title: 'To Kill a Mockingbird',
    original_title: 'To Kill a Mockingbird',
    authors: ['Harper Lee'],
    original_publication_year: 1960,
    average_rating: 4.7,
    ratings_count: 5,
    ratings_1: 4.7,
    ratings_2: 5.0,
    ratings_3: 4.8,
    ratings_4: 4.4,
    ratings_5: 5.0,
    image_url: '/assets/images/mockingbird.jpg',
    small_image_url: '/assets/images/mockingbird.jpg',
  },
  {
    isbn13: '9780451524935',
    title: '1984',
    original_title: 'Nineteen Eighty-Four',
    authors: ['George Orwell'],
    original_publication_year: 1949,
    average_rating: 4.7,
    ratings_count: 5,
    ratings_1: 4.7,
    ratings_2: 5.0,
    ratings_3: 4.8,
    ratings_4: 4.4,
    ratings_5: 5.0,
    image_url: '/assets/images/1984.jpg',
    small_image_url: '/assets/images/1984.jpg',
  },
  {
    isbn13: '9780141439518',
    title: 'Pride and Prejudice',
    original_title: 'Pride and Prejudice',
    authors: ['Jane Austen'],
    original_publication_year: 1813,
    average_rating: 4.7,
    ratings_count: 5,
    ratings_1: 4.7,
    ratings_2: 5.0,
    ratings_3: 4.8,
    ratings_4: 4.4,
    ratings_5: 5.0,
    image_url: '/assets/images/pride.jpg',
    small_image_url: '/assets/images/pride.jpg',
  },
];
